### ISSUE TITLE
SDN - vanet.py

### ISSUE THREAD

**Issue by RAMPRASATH29** [ramonfontes/reproducible-research#12]
import os
import time
import matplotlib.pyplot as plt
from mininet.log import setLogLevel
from mininet.node import Controller, OVSKernelSwitch
from mininet.wifi.node import OVSKernelAP
from mininet.wifi.net import Mininet_wifi
from mininet.wifi.cli import CLI_wifi

import file not working..
if you have whole import for vanet.py .

**Comment by ramonfontes** [comment]
https://github.com/ramonfontes/reproducible-research/blob/master/mininet-wifi/IEEE-Access-2017/README.md#please-refer-to-the-manual-of-mininet-wifi-to-reproduce-this-paper-consider-to-run-mininet-wifi-with-this-commit
