### ISSUE TITLE
SWITCHON-2015 allWirelessNetworksAroundUs.py 

### ISSUE THREAD

**Issue by RAMPRASATH29** [ramonfontes/reproducible-research#13]
not working 
their is no seed import in mininet-wifi
seed ?

**Comment by ramonfontes** [comment]
What?? What did you mean about "not working"? Could you clarify your question please?

**Comment by ramonfontes** [comment]
Fixed! https://github.com/ramonfontes/reproducible-research/commit/00056e0105b649d6b919140489d68af7c67647d3
