### ISSUE TITLE
IEEE-Access-2017 vanet.py

### ISSUE THREAD

**Issue by RAMPRASATH29** [ramonfontes/reproducible-research#14]
sudo rm -r /usr/local/lib/python2.7/dist-packages/mininet*
 i have remove python 2.7 but it has not function (git reset --hard b43af65) next command.

**Comment by ramonfontes** [comment]
Can you be clearer with your questions?

**Comment by RAMPRASATH29** [comment]
i have try this code vanet.py.
from mininet-wifi - sudo rm -r /usr/local/lib/python2.7/dist-packages/mininet*
Mininet file has removed.
next i paste (git reset --hard b43af65)
it doesn't taken to next step : error (not reset)

**Comment by RAMPRASATH29** [comment]
> Can you be clearer with your questions? What are you doing? Why did you remove python2.7??

sudo rm -r /usr/local/lib/python2.7/dist-packages/mininet*

 in this command the python file has remove from mininet-wifi

**Comment by ramonfontes** [comment]
Closing the issue due to its non-confirmation and mis described problem.

**Comment by RAMPRASATH29** [comment]
i you have file for vanet.py (whole file to compile ) running file .
In mininet-wifi ( vanet.py ) compress the file send to my mail address (84ramprasath@gmail.com).
