### ISSUE TITLE
Invalid literal for int()

### ISSUE THREAD

**Issue by htahir6200** [ramonfontes/reproducible-research#2]
Hello, i am facing the following error while running the vanet.py example.
![error](https://user-images.githubusercontent.com/22287362/39770263-7650d66a-5329-11e8-8fd5-41cdf8caca01.png)

**Comment by ramonfontes** [comment]
Please check if you can get TX/RX packets with the command available at
https://github.com/ramonfontes/reproducible-research/blob
/master/mininet-wifi/IEEE-Access-2017/vanet.py#L123. I suppose it is not
working with your kernel version and some adjusts are needed.

2018-05-08 13:37 GMT-03:00 htahir6200 <notifications@github.com>:

**Comment by htahir6200** [comment]
Which kernel version will work for the vanet example. Secondly, the above link shows 404.

**Comment by ramonfontes** [comment]
Sorry. This is the link
<https://github.com/ramonfontes/reproducible-research/blob/master/mininet-wifi/IEEE-Access-2017/vanet.py#L123>.
It will work in any kernel version, however, few adjusts are needed in
order to get tx/rx packets as well as the amount of data (in bytes).

2018-05-08 13:50 GMT-03:00 htahir6200 <notifications@github.com>:

**Comment by htahir6200** [comment]
Do i need to make changes insode my OS kernal or inside the vanet.py file? Can you please suggest what kind of changes i have to made?

**Comment by htahir6200** [comment]
I am not to able to see the tx packets. I have also checked the packet-switch.vanetdata file which also shows a column of "errors:0" in it.

**Comment by ramonfontes** [comment]
So, you have to modify the command in order to get tx packets, etc.

**Comment by htahir6200** [comment]
It says Bond0 interface not found.

**Comment by ramonfontes** [comment]
Cannot you replace bond0 with any other interface you have?? :( is the command and concept behind the command too difficult to comprehend?

**Comment by htahir6200** [comment]
It was just a print issue.i have resolved it. Tahnk you.

**Comment by SUFEIYA** [comment]
Can turn the Car0 into any car? and how to change the code? Thanks!
