### ISSUE TITLE
change the sender to any car

### ISSUE THREAD

**Issue by SUFEIYA** [ramonfontes/reproducible-research#3]
Can change the sender to any car ? not only the car0. For example, the first rule , the sender is car0, the second rule the sender is car1
Can change the receiver is car ?

**Comment by ramonfontes** [comment]
Yes, for sure. Why not?

**Comment by SUFEIYA** [comment]
why car0-wlan0 to rsu1, car0-wlan1 to the eNodeB2?
I know car3-wlan0 to eNodeB1 because of car[3].cmd('ifconfig car3-wlan0 200.0.10.150')

**Comment by ramonfontes** [comment]
Sorry. I didn't get you... Could you clarify your question?

**Comment by SUFEIYA** [comment]
![default](https://user-images.githubusercontent.com/31503612/42693723-9edac702-86e2-11e8-9461-a6b223387cc7.png)

**Comment by ramonfontes** [comment]
We didn't use such node in our experiment. Did you read the paper?

**Comment by SUFEIYA** [comment]
The code from https://github.com/ramonfontes/reproducible-research/blob/master/mininet-wifi/IEEE-Access-2017/vanet.py， i read your article 《From Theory to Experimental Evaluation: Resource Management in Software-Defined Vehicular Networks》.
Now i want to change the sender not only the car0, for example, the first rule the sender is car0, the second rule the sender is car1......
i don't know how to do it ?

**Comment by SUFEIYA** [comment]
Excuse me,
Your code is 
![default](https://user-images.githubusercontent.com/31503612/42732268-e91129b4-8850-11e8-85d7-febba98d9dfa.png)
I change it
![default](https://user-images.githubusercontent.com/31503612/42732277-0f5f69f0-8851-11e8-98a3-dd17d97d611e.png)
But the result is wrong, it is because 
![default](https://user-images.githubusercontent.com/31503612/42732287-4543f068-8851-11e8-8e2e-9c08512b5d11.png)
no car link to eNodeB1
I can't understand , why car0 can link to RSU1 and eNodeB2, but can't link to eNodeB1
Hope your reply!! Thanks

**Comment by ramonfontes** [comment]
Dear,

Please use "iw" to check assocations.

**Comment by SUFEIYA** [comment]
Excuse me again,
In your code , what is eNodeB1's，eNodeB2's, rsu1's ip ?
Thank you for your help !

**Comment by SUFEIYA** [comment]
Sorry, excuse me  again,
What do you mean wlans=2  in the code of 
![default](https://user-images.githubusercontent.com/31503612/42794286-90e3792a-89b0-11e8-894a-cb713b4a7390.png)
Thanks for your help !

**Comment by ramonfontes** [comment]
Dear,

I suggest you to read the user manual of mininet-wifi.
