### ISSUE TITLE
Error in executing Propagation Model.py

### ISSUE THREAD

**Issue by harualhassan** [ramonfontes/reproducible-research#4]
Creating nodes
*** Configuring wifi nodes
*** Adding Link
Associating sta1-wlan0 to ap1
Associating sta2-wlan0 to ap1
*** Starting network
*** Configuring nodes
Traceback (most recent call last):
  File "propagationModel1.py", line 53, in <module>
    topology()
  File "propagationModel1.py", line 42, in topology
    sta1.moveStationTo(pos)
AttributeError: 'Station' object has no attribute 'moveStationTo'

Please How Can I clear this Error

**Comment by ramonfontes** [comment]
Please try `setPosition()` instead of `moveStationTo()`.
