### ISSUE TITLE
Constant rssi in executing Propagation Model.py

### ISSUE THREAD

**Issue by harualhassan** [ramonfontes/reproducible-research#5]
Kindly assist me to sort the problem in the script below: As the node sta2 move away from the ap1 the rssi should decrease corresponding to the position of sta2. Although sta2 moves away from ap1 the rssi stays constant at -19dbm. May i know the problem in the script why rssi is not decreasing corresponding to the movement of sta2 away from ap1: Below is the script and the executed output ?

SCRIPT:
#!/usr/bin/python

"Propagation Model Demo"

from mininet.log import setLogLevel, info
from mininet.node import Controller
from mn_wifi.net import Mininet_wifi
from mn_wifi.node import OVSKernelAP
from mn_wifi.cli import CLI_wifi

def topology():
    "Create a network."
    net = Mininet_wifi( controller=Controller, accessPoint=OVSKernelAP )

    info("*** Creating nodes\n")
    ap1 = net.addAccessPoint( 'ap1', ssid='ssid_ap1', txpower='15' , mode='g', channel='1' , position='10,10,0' )
    sta1 = net.addStation( 'sta1', ip='192.168.0.1/24', txpower='15' , position='8,10,0' )
    sta2 = net.addStation( 'sta2', ip='192.168.0.2/24', txpower='15' , position='11.36,10,0' )

    net.propagationModel(model='logDistance', exp=3, sL=1)
    # net.propagationModel('ITUPropagationLossModel', pL=50 )
    # net.propagationModel('ITUPropagationLossModel' )
    # net.propagationModel('twoRayGroundPropagationLossModel')
    # net.propagationModel('friisPropagationLossModel', sL=2)

    info("*** Configuring wifi nodes\n")
    net.configureWifiNodes()

    info("*** Adding Link\n")
    net.addLink(sta1, ap1)
    net.addLink(sta2, ap1)

    net.plotGraph(max_x=30, max_y=30)

    info("*** Starting network\n")
    net.build()

    for i in range(1,9):
        x = 10+i*1.36
        y = 10
        z = 0
        
        pos = '%s,%s,%s' % (x,y,z)    
        sta2.setPosition(pos)
                
        info(sta2.params['rssi'][0])
        info("*** RSSI\n")
        
        info(sta2.params['position'][0])
        info("*** POSITION\n")
        

    info("*** Running CLI\n")
    CLI_wifi( net )

    info("*** Stopping network\n")
    net.stop()

if __name__ == '__main__':
    setLogLevel( 'info' )
topology()
EXECUTED OUTPUT
haru@haru-HP-Laptop-15-bs0xx:~/mininet-wifi/examples$ sudo python propagationModel2.py
*** Creating nodes
*** Configuring wifi nodes
*** Adding Link
Associating sta1-wlan0 to ap1
Associating sta2-wlan0 to ap1
*** Starting network
*** Configuring nodes
-19.0*** RSSI
11.36*** POSITION
-19.0*** RSSI
12.72*** POSITION
-19.0*** RSSI
14.08*** POSITION
-19.0*** RSSI
15.44*** POSITION
-19.0*** RSSI
16.8*** POSITION
-19.0*** RSSI
18.16*** POSITION
-19.0*** RSSI
19.52*** POSITION
-19.0*** RSSI
20.88*** POSITION
*** Running CLI
*** Starting CLI:
mininet-wifi>

**Comment by ramonfontes** [comment]
You don't need to use addLink() in scenarios with mobility. I think it works if you remove addLink().

**Comment by harualhassan** [comment]
thanks much it works
